### PR TITLE
fix titles of financial graphs

### PR DESCRIPTION
**Pull request by robynstuart**

### CODE REVIEW

**Comment by Ashalynd** [comment]
@DrMud how did you verify that it works? Did you check this in UI?

**Comment by DrMud** [comment]
@Ashalynd my apologies, that was a mistake on my part. I tried to revert the merge, but not sure if that's gone through and if anyone else can still verify and merge the original pull request.

**Comment by Ashalynd** [comment]
No problem, I will check this. Unfortunately reverting the merge can't be done easily now because other things are already merged (I haven't noticed this one), hopefully the changes here are small.

**Comment by DrMud** [comment]
Thankfully was a small one: 5 lines

**Pull request merged**
