### PR TITLE
Feature/463 2 handle the exceptions in async calculations gracefully

### PR DESCRIPTION
**Pull request by Ashalynd**
https://trello.com/c/whKz15tP/463-2-handle-the-exceptions-in-async-calculations-gracefully
(attention: this pr contains database migration)

P.S. it's more about "bubbling up" the exception from the async thread.

This should also fix https://trello.com/c/voRMG5ng/340-1-potential-problem-with-optimization

### CODE REVIEW

**Comment by Ashalynd** [comment]
To be reviewed preferably either by a fullstack developer or by a frontender who can do something about "Possible improvement (FE)" mentioned on the card.

**Comment by nikgraf** [comment]
@Ashalynd 

Just tried the migration & it failed. Am I doing something wrong?

    ➜  Optima git:(feature/463-2-handle-the-exceptions-in-async-calculations-gracefully) migrate upgrade postgresql://optima:optima@localhost:5432/optima server/db/
    6 -> 7... 
    SQL script server/db/versions/007_work_log_postgresql_upgrade.sql failed: (ProgrammingError) relation "work_log" already exists
     'CREATE TABLE work_log (\n    id SERIAL PRIMARY KEY,\n    work_type character varying(32),\n    project_id integer,\n    start_time timestamp with time zone DEFAULT now(),\n    stop_time timestamp with time zone,\n    status work_status,\n    error text,\n  CONSTRAINT work_log_project_id_fkey FOREIGN KEY (project_id) \n    REFERENCES projects(id) MATCH SIMPLE\n    ON UPDATE NO ACTION ON DELETE NO ACTION\n);' {}
    Traceback (most recent call last):
      File "/usr/local/bin/migrate", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python2.7/site-packages/migrate/versioning/shell.py", line 209, in main
        ret = command_func(**kwargs)
      File "/usr/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 186, in upgrade
        return _migrate(url, repository, version, upgrade=True, err=err, **opts)
      File "<string>", line 2, in _migrate
      File "/usr/local/lib/python2.7/site-packages/migrate/versioning/util/__init__.py", line 160, in with_engine
        return f(*a, **kw)
      File "/usr/local/lib/python2.7/site-packages/migrate/versioning/api.py", line 366, in _migrate
        schema.runchange(ver, change, changeset.step)
      File "/usr/local/lib/python2.7/site-packages/migrate/versioning/schema.py", line 93, in runchange
        change.run(self.engine, step)
      File "/usr/local/lib/python2.7/site-packages/migrate/versioning/script/sql.py", line 45, in run
        conn.execute(statement)
      File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 721, in execute
        return self._execute_text(object, multiparams, params)
      File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 870, in _execute_text
        statement, parameters
      File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
        context)
      File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
        exc_info
      File "/usr/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
        reraise(type(exception), exception, tb=exc_tb)
      File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
        context)
      File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.ProgrammingError: (ProgrammingError) relation "work_log" already exists
     'CREATE TABLE work_log (\n    id SERIAL PRIMARY KEY,\n    work_type character varying(32),\n    project_id integer,\n    start_time timestamp with time zone DEFAULT now(),\n    stop_time timestamp with time zone,\n    status work_status,\n    error text,\n  CONSTRAINT work_log_project_id_fkey FOREIGN KEY (project_id) \n    REFERENCES projects(id) MATCH SIMPLE\n    ON UPDATE NO ACTION ON DELETE NO ACTION\n);' {}

**Comment by Ashalynd** [comment]
@nikgraf yes, you should have stopped the app before switching to that branch, otherwise it makes new table automatically

**Comment by nikgraf** [comment]
Works great!

**Pull request merged**
