### PR TITLE
Optimization multiple years

### PR DESCRIPTION
**Pull request by cliffckerr**

### CODE REVIEW

**Comment by nikgraf** [comment]
@cliffckerr I tried running optimisations with a constant budget & time varying options turned on. It failed with this exception:

    Traceback (most recent call last):
      File "/Users/nikgraf/Projects/startersquad/Optima/server/src/optima/async_calculate.py", line 154, in run
        D = self.func(D, **self.args)
      File "/Users/nikgraf/Projects/startersquad/Optima/server/src/sim/optimize.py", line 235, in optimize
        alloc = timevarying(params, ntimepm=ntimepm, nprogs=nprogs, tvec=D.opt.partvec, totalspend=totalspend) #Regenerate allocation
      File "/Users/nikgraf/Projects/startersquad/Optima/server/src/sim/timevarying.py", line 25, in timevarying
        raise Exception('Invalid number of parameters to define allocations over time')
    Exception: Invalid number of parameters to define allocations over time

**Comment by nikgraf** [comment]
@cliffckerr also when running a variable budget it fails with this error:

    Traceback (most recent call last):
      File "/Users/nikgraf/Projects/startersquad/Optima/server/src/optima/async_calculate.py", line 154, in run
        D = self.func(D, **self.args)
      File "/Users/nikgraf/Projects/startersquad/Optima/server/src/sim/optimize.py", line 275, in optimize
        optparams, fval, exitflag, output = ballsd(objectivecalc, optimparams, options=options, xmin=parammin, timelimit=timelimit, fulloutput=True, verbose=verbose)
      File "/Users/nikgraf/Projects/startersquad/Optima/server/src/sim/ballsd.py", line 94, in ballsd
        fval = function(x) if options is None else function(x,options) # Calculate initial value of the objective function
      File "/Users/nikgraf/Projects/startersquad/Optima/server/src/sim/optimize.py", line 34, in objectivecalc
        thisalloc = multiyear(optimparams, years=options.years, totalspends=options.totalspends, nprogs=options.nprogs, tvec=options.D.opt.partvec)
      File "/Users/nikgraf/Projects/startersquad/Optima/server/src/sim/timevarying.py", line 151, in multiyear
        thisalloc *= totalspends[max(0,y-1)] / float(sum(thisalloc))
    KeyError: 0

**Comment by cliffckerr** [comment]
Hmm I think that might be FE -> BE (i.e. API) issues

**Comment by Ashalynd** [comment]
Big changes in API (different way of running asynchronous calculations). Seems to be working. UI changes in optimizations page pending.

**Pull request merged**
